title: The Praxis Intitiative
description: Teaching Knowledge Engineering
logo: assets/images/tpi-logo.png
show_downloads: false

remote_theme: pages-themes/dinky@v0.2.0
plugins:
    - jekyll-remote-theme
